命令稿啟動於 2018年03月16日 上午 10:54:06
]0;~
[32muser@MSI [33m~[0m
$ ws[Khoami [K;pwd
user
/home/user
]0;~
[32muser@MSI [33m~[0m
$ git config-l
git: 'config-l' is not a git command. See 'git --help'.
]0;~
[32muser@MSI [33m~[0m
$ git config -l
user.email=zxcasdqwe0258@yahoo.com.tw
user.name=CcepWang
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
]0;~
[32muser@MSI [33m~[0m
$ git clone  https://github.com/CcepWang/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;~
[32muser@MSI [33m~[0m
$ exit

命令稿已於 2018年03月16日 上午 10:55:51
 完成